application:
  protocol: https
  host: 0.0.0.0
  base_url: "https://johnwrites-actix-backend.onrender.com"

debug: false

secret:
  secret_key: ""
  token_expiration: 0
  hmac_secret: ""

frontend_url: ""
