application:
  protocol: https
  host: 0.0.0.0
  base_url: "https://auth-actix-web-sveltekit.fly.dev"

debug: false

secret:
  secret_key: ""
  token_expiration: 15
  hmac_secret: ""

frontend_url: ""
